theme: jekyll-theme-architect

source: ./
destination: ./_site

include: [".txt", ".TXT", ".md"]

baseurl: "/articles"

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
